// Package localstack provides LocalStack integration for offline AWS testing
package localstack

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
)

// LocalStack configuration constants
const (
	// LocalStackEndpoint is the default LocalStack gateway endpoint
	LocalStackEndpoint = "http://localhost:4566"

	// LocalStackRegion is the default region for LocalStack testing
	LocalStackRegion = "us-west-2"

	// LocalStackAccessKey is the dummy access key for LocalStack
	LocalStackAccessKey = "test"

	// LocalStackSecretKey is the dummy secret key for LocalStack
	LocalStackSecretKey = "test"

	// EnvVarEnabled is the environment variable to enable LocalStack mode
	EnvVarEnabled = "PRISM_USE_LOCALSTACK"

	// EnvVarEndpoint allows overriding the LocalStack endpoint
	EnvVarEndpoint = "LOCALSTACK_ENDPOINT"

	// ConfigFilePath is the path to LocalStack resource configuration.
	// The init scripts write this to /var/lib/localstack/ inside the container,
	// which is volume-mounted to /tmp/localstack/ on the host.
	ConfigFilePath = "/tmp/localstack/prism-localstack-config.json"
)

// Config holds LocalStack-specific resource configuration
// This is generated by the initialization scripts when LocalStack starts
type Config struct {
	VPCID             string            `json:"vpc_id"`
	InternetGatewayID string            `json:"internet_gateway_id"`
	SubnetIDs         []string          `json:"subnet_ids"`
	SecurityGroupID   string            `json:"security_group_id"`
	AMIIDs            map[string]string `json:"ami_ids"`
	KeyPair           string            `json:"key_pair"`
	EFSFileSystemID   string            `json:"efs_file_system_id,omitempty"`
	EFSMountTargetIDs []string          `json:"efs_mount_target_ids,omitempty"`
}

// IsLocalStackEnabled returns true if LocalStack mode is enabled via environment variable
func IsLocalStackEnabled() bool {
	enabled := os.Getenv(EnvVarEnabled)
	return enabled == "true" || enabled == "1"
}

// GetEndpoint returns the LocalStack endpoint to use
// Checks LOCALSTACK_ENDPOINT environment variable, falls back to default
func GetEndpoint() string {
	if endpoint := os.Getenv(EnvVarEndpoint); endpoint != "" {
		return endpoint
	}
	return LocalStackEndpoint
}

// LoadConfig loads LocalStack resource configuration from the config file
// This file is created by the initialization scripts and contains VPC IDs, AMI IDs, etc.
func LoadConfig() (*Config, error) {
	data, err := os.ReadFile(ConfigFilePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read LocalStack config file %s: %w (run 'docker-compose up' in test/localstack)", ConfigFilePath, err)
	}

	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse LocalStack config: %w", err)
	}

	return &cfg, nil
}

// NewAWSConfig creates an AWS configuration for LocalStack
// This configures the AWS SDK to use LocalStack endpoints and credentials
func NewAWSConfig(ctx context.Context) (aws.Config, error) {
	endpoint := GetEndpoint()

	// Create custom endpoint resolver for all services
	customResolver := aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:               endpoint,
			SigningRegion:     LocalStackRegion,
			HostnameImmutable: true,
		}, nil
	})

	// Load AWS configuration with LocalStack settings.
	// Explicitly skip shared config/credentials files so AWS_PROFILE in the
	// environment doesn't cause the SDK to try loading a non-existent profile.
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(LocalStackRegion),
		config.WithEndpointResolverWithOptions(customResolver),
		config.WithSharedConfigFiles([]string{}),
		config.WithSharedCredentialsFiles([]string{}),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			LocalStackAccessKey,
			LocalStackSecretKey,
			"", // session token not needed
		)),
	)
	if err != nil {
		return aws.Config{}, fmt.Errorf("failed to load LocalStack AWS config: %w", err)
	}

	return cfg, nil
}

// NewAWSConfigWithProfile creates an AWS configuration with custom profile/region support
// This is used by the Manager when profile options are provided
func NewAWSConfigWithProfile(ctx context.Context, profile, region string) (aws.Config, error) {
	if !IsLocalStackEnabled() {
		// Not using LocalStack, load normal AWS config with profile/region
		cfgOpts := []func(*config.LoadOptions) error{}

		if profile != "" {
			cfgOpts = append(cfgOpts, config.WithSharedConfigProfile(profile))
		}

		if region != "" {
			cfgOpts = append(cfgOpts, config.WithRegion(region))
		}

		return config.LoadDefaultConfig(ctx, cfgOpts...)
	}

	// LocalStack mode - ignore profile, use LocalStack config
	endpoint := GetEndpoint()

	// Use provided region or fall back to default LocalStack region
	targetRegion := region
	if targetRegion == "" {
		targetRegion = LocalStackRegion
	}

	// Custom endpoint resolver
	customResolver := aws.EndpointResolverWithOptionsFunc(func(service, awsRegion string, options ...interface{}) (aws.Endpoint, error) {
		return aws.Endpoint{
			URL:               endpoint,
			SigningRegion:     targetRegion,
			HostnameImmutable: true,
		}, nil
	})

	// Load AWS configuration with LocalStack settings.
	// Explicitly skip shared config/credentials files so that environment
	// variables like AWS_PROFILE (e.g. "localstack") don't cause the SDK to
	// try loading a non-existent profile from ~/.aws/config.
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion(targetRegion),
		config.WithEndpointResolverWithOptions(customResolver),
		config.WithSharedConfigFiles([]string{}),
		config.WithSharedCredentialsFiles([]string{}),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
			LocalStackAccessKey,
			LocalStackSecretKey,
			"",
		)),
	)
	if err != nil {
		return aws.Config{}, fmt.Errorf("failed to load LocalStack AWS config: %w", err)
	}

	return cfg, nil
}

// GetAMI returns the LocalStack AMI ID for a given OS distribution and architecture
// Example: GetAMI("ubuntu-22.04-x86_64") returns the mock Ubuntu 22.04 x86_64 AMI
func (c *Config) GetAMI(key string) (string, error) {
	amiID, exists := c.AMIIDs[key]
	if !exists {
		return "", fmt.Errorf("AMI not found for key: %s (available: %v)", key, c.availableAMIKeys())
	}
	return amiID, nil
}

// availableAMIKeys returns a list of available AMI keys for error messages
func (c *Config) availableAMIKeys() []string {
	keys := make([]string, 0, len(c.AMIIDs))
	for k := range c.AMIIDs {
		keys = append(keys, k)
	}
	return keys
}

// GetDefaultSubnetID returns the first available subnet ID
// This is useful for tests that don't care about specific subnet selection
func (c *Config) GetDefaultSubnetID() (string, error) {
	if len(c.SubnetIDs) == 0 {
		return "", fmt.Errorf("no subnets available in LocalStack configuration")
	}
	return c.SubnetIDs[0], nil
}

// Validate checks that all required LocalStack resources are configured
func (c *Config) Validate() error {
	if c.VPCID == "" {
		return fmt.Errorf("VPC ID not set in LocalStack configuration")
	}
	if len(c.SubnetIDs) == 0 {
		return fmt.Errorf("no subnets configured in LocalStack")
	}
	if c.SecurityGroupID == "" {
		return fmt.Errorf("security group ID not set in LocalStack configuration")
	}
	if len(c.AMIIDs) == 0 {
		return fmt.Errorf("no AMIs configured in LocalStack")
	}
	if c.KeyPair == "" {
		return fmt.Errorf("key pair not set in LocalStack configuration")
	}
	return nil
}
